"""initial schema

Revision ID: 113b09df4534
Revises: 
Create Date: 2026-05-31 05:45:51.155692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113b09df4534'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'client_admin', 'assessor', 'viewer', name='user_role'), nullable=False),
    sa.Column('organisation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assessments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organisation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', name='assessment_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('question_id', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('answer_value', sa.Integer(), nullable=False),
    sa.Column('answer_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('maturity_tier', sa.Integer(), nullable=False),
    sa.Column('maturity_label', sa.String(length=50), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('responses')
    op.drop_table('assessments')
    op.drop_table('users')
    op.drop_table('organisations')
    # ### end Alembic commands ###
