"""add ai analysis and roadmap persistence

Revision ID: 43312c3613ff
Revises: e590790c0b5c
Create Date: 2026-08-18 01:26:54.381830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43312c3613ff'
down_revision = 'e590790c0b5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('analysis_status', sa.String(length=20), nullable=True))
    op.add_column('results', sa.Column('roadmap_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'roadmap_status')
    op.drop_column('results', 'analysis_status')
    # ### end Alembic commands ###
