"""add ai_analysis and ai_roadmap to results

Revision ID: e590790c0b5c
Revises: 113b09df4534
Create Date: 2026-08-18 01:23:52.067325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e590790c0b5c'
down_revision = '113b09df4534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('ai_analysis', sa.JSON(), nullable=True))
    op.add_column('results', sa.Column('ai_roadmap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'ai_roadmap')
    op.drop_column('results', 'ai_analysis')
    # ### end Alembic commands ###
